### ISSUE TITLE
Maintain scroll position

### ISSUE THREAD

**Issue by Phatsuo** [MohammadYounes/AlertifyJS#121]
Same as closed issue #49.

I am using Chrome I just added 

```
html, body {
   height: 100%;
}
```

to my css, and now the page scrolls to the top every time an alert is closed.

The workarounds in issue #49 do not work (the one where you save lastX and lastY, and the customAlert).

**Comment by MohammadYounes** [comment]
The workaround in #49 is no longer required, as maintaining scroll position was integrated into the lib (158b360ab5f52053e3ba23a48fb81790ceaaa635).

Would you provide an online sample presenting the issue ? I tried [this](http://codepen.io/anon/pen/kkozdB) and all working fine!

**Comment by Phatsuo** [comment]
Thanks for the quick reply!

Here you go. Click the div instead.

http://codepen.io/anon/pen/ALQBoz

**Comment by MohammadYounes** [comment]
Thanks for the sample!

Your scroll appears to be lost due to the `div` being unable to receive focus, so the focus goes to the `body` element.

There are two direct fixes for this:

 1. Disable [maintainFocus](http://alertifyjs.com/guide.html#defaults) option:  `alertify.defaults.maintainFocus = false;`

 2. Give your `div` the ability to receive focus: `<div tabindex="-1" style="outline:none;"> ... </div>`

>  a negative tabindex value means that the element should be focusable, but should not be reachable via sequential keyboard navigation. ([mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex))

See http://codepen.io/anon/pen/BLwarx

**Comment by Phatsuo** [comment]
Thanks, I will try it today.

**Comment by Phatsuo** [comment]
Thanks. `alertify.defaults.maintainFocus = false;` worked.

**Comment by MohammadYounes** [comment]
Thanks for the feedback!

**Comment by Phatsuo** [comment]
BTW - on the same Pen, you can see the scrollbar disappears when the alert appears, and reappears when it closes. With a page full of content, this causes everything on the page to jump around a little bit when the alert appears, and when it closes. Can that be controlled?

**Comment by MohammadYounes** [comment]
Yes, simply enable [`preventBodyShift`](http://alertifyjs.com/guide.html#defaults) option.
