### ISSUE TITLE
Q: Creating multiple custom dialogs having different forms.

### ISSUE THREAD

**Issue by alokg1019** [MohammadYounes/AlertifyJS#152]
Hi,
I have 6 buttons on a page. On clicking each of the button, I need to show a dialog box, where user can fill in a small form. I'm trying to handle all the forms with just one custom dialog, by using the dialog in singleton mode since only 1 form can be opened at a time. When the user needs to open a second form, the current dialog must be closed and then he/she can open the next form. I can simply use the same dialog to show the different contents.
However, when I open a second form, the **div** holding the previous form is replaced by the new form. How can I save the **div** containing my previous form from getting removed from the page when I open another form?
I noticed that all the alterifyjs elements are kept at the bottom of the page. 
Do I have to use my own logic to make sure I save the contents at a separate place before the second form gets loaded?

Including question link to stackoverflow:
https://stackoverflow.com/questions/45572318/creating-multiple-custom-dialogs-having-different-forms-using-alterifyjs-library

**Comment by MohammadYounes** [comment]
Hi,

Yes, this need to be managed by you.  But since you already have a custom dialog, such function is straight forward.

All you need to do is to save a placeholder for the original element location and then restore it on close.

See [updated fiddle](https://jsfiddle.net/tu3mq98x/2/).

I also [answered](https://stackoverflow.com/a/45575949/328072) your SO question with a [different solution](https://jsfiddle.net/tu3mq98x/3/).
