### ISSUE TITLE
Confirm Dialog invoking previous onok and oncancel callbacks, which causes unexpected behavior

### ISSUE THREAD

**Issue by pwaivers** [MohammadYounes/AlertifyJS#177]
When calling alertify.confirm(...) without an onok or oncancel callback, it will invoke the last onok or oncancel functions that were provided to the function.  For example, check out this Fiddle: http://jsfiddle.net/z5rg075z/.  Try the following workflow:

1. Click "Ajax Call DELETE"
2. Press Cancel
3. Click "Do Nothing"
4. Press OK

Then the delete AJAX call that was passed into the DELETE confirm is then invoked, instead of nothing happening like we would expect.  You can press these confirm buttons in all different orders to test out the bad functionality.  

**Is this expected behavior?**

**Comment by MohammadYounes** [comment]
Yes, This is the expected behavior.  All of the built-in dialogs are singletons, they will maintain their options unless destroyed.  

Either clear the callbacks by setting them again to `null` or `undefined` or use  [`.destroy()`](http://alertifyjs.com/confirm/destroy) method to reset all options.

Thanks!

> Dup: #154
