### ISSUE TITLE
Callback for completely closing confirm dialog (including animation)

### ISSUE THREAD

**Issue by Wizard13** [MohammadYounes/AlertifyJS#178]
Hi!
I have small situation where I need to focus on an element after closing the confirmation dialog. I am unable to do so, because after closing the confirmation dialog, the browser transfers the focus to the button that initiated the confirmation dialog. So, I need to find a way to focus on my element AFTER animation finishes, because if I do the focus in the function callback, it is removed by the browser after animation finishes.

I have made a JSFiddle to illustrate this here: https://jsfiddle.net/hcmy8sfL/2/
After pressing button "a", I can focus in the textarea. After pressing button "b", I can focus only momentarily in the textarea when I hit "Cancel", because the browser focuses again in button "b". When I hit "OK", I can focus in the textarea because I've set a timeout for the focus 1 second afterwards, but I don't like this solution.
Is there a way to know when the dialog has completely closed, so as to execute my focus?

**Comment by MohammadYounes** [comment]
Hello @Wizard13 

This is due to the dialog trying to maintain focus of the element that triggered it! You can disable this globally by setting [`alertify.defaults.maintainFocus = false;`](http://alertifyjs.com/guide.html#defaults) or just for this dialog by clearing the active element reference [`this.__internal.activeElement = null;`](https://jsfiddle.net/bs25ecov/)

Thanks!

> Dup #64
