### ISSUE TITLE
How to reset defaults after using the .set() on a prompt or set in a non-global scope

### ISSUE THREAD

**Issue by rshingleton** [MohammadYounes/AlertifyJS#179]
I have an authentication prompt in a Vue app:
```` 
alertify.prompt('Command Authentication', 'Password', ''
            , function (evt, pwd) {
            }, function () {
                alertify.error('Canceled')
            }).set('type', 'password');
````
This works fine, however any subsequent prompts after this is done now have the input field as a password type. Is there an easy way to reset this or to set the field type in a non-global fashion?

I would really hate to have to set('type', 'text') all over the place when I need to use a default prompt.

I think it would be nice to be able to pass settings on the instance, such as:

```` 
alertify.prompt(<title>,<label>,<function>,<function>,{settings})
````

**Comment by MohammadYounes** [comment]
@rshingleton This is the expected behavior as all of the built-in dialogs are singletons, they will maintain their options unless destroyed.

The easiest way is to revert changes when the dialog is closed

```js
alertify.prompt('Command Authentication', 'Password', '', function (evt, pwd) {},
      function () { alertify.error('Canceled')})
  .set(
    {
       type: 'password',
       onclose: function(){ 
         this.set({type:'text', value: ''});
       }
    });
````


Another way is to use  [`.destroy()`](http://alertifyjs.com/prompt/destroy) method to reset all options to their defaults.  Finally, you can create a [sub-dialog](http://alertifyjs.com/factory.html#factory) and use hooks to reset your options.


>Dup: #177, #154
