### ISSUE TITLE
mobile layer tips can't center.

### ISSUE THREAD

**Issue by PHPJourney** [MohammadYounes/AlertifyJS#189]
https://youtu.be/W2wtGvKxCPU
i create an movie show this error.

please give me feedback. thanks .

i wanna get official website check setting solve this question. but i cannot find it.

**Comment by PHPJourney** [comment]
i just use postion to button-left;

        alertify.set('notifier','position', 'bottom-left');
center and right cannot use.

**Comment by MohammadYounes** [comment]
@PHPJourney This is because you are including all CSS files, You just need the main file and one theme (either default or right-to-left ). In your case, you only need the first two:

![image](https://user-images.githubusercontent.com/4712046/41613904-ab6c12fa-73ff-11e8-8ef0-0bed6831a1a9.png)

Thanks!

**Comment by PHPJourney** [comment]
ok .let me try.

**Comment by PHPJourney** [comment]
@MohammadYounes 
all right. it's ok. thanks
