### ISSUE TITLE
re-focus input after close dialog

### ISSUE THREAD

**Issue by LucasBertrand** [MohammadYounes/AlertifyJS#64]
Hi !
I did install this awesome framework and all work very fine exept for one thing :
I created a light WYSIWYG HTML editor. When i click on the link button for exemple, a prompt dialog ask the url to the user. 
After validation, my script give the focus to the text-field but it's canceled after the dialog is completly disapear.
The onClose event is fire before the finish of the css transition.
I wouldn't want to hack this problem with a setTimeout.
Have you got suggestions ?
Thanks a lot and congratulations for this awesome work !

**Comment by MohammadYounes** [comment]
Hi

Can you isolate this into a test case? You can fork this [codepen](http://codepen.io/anon/pen/raohK) or this [jsfiddle](http://jsfiddle.net/g2o52zq7/) to get started!

Thanks.

**Comment by LucasBertrand** [comment]
It's here : http://jsfiddle.net/7q397fx4/

**Comment by MohammadYounes** [comment]
This is due to dialog trying to maintain focus of the element that triggered it! You can disable this globally by setting [`alertify.defaults.maintainFocus = false;`](http://jsfiddle.net/7q397fx4/2/) or just for this dialog by clearing the active element reference [`this.__internal.activeElement = null;`](http://jsfiddle.net/7q397fx4/3/)

**Comment by LucasBertrand** [comment]
That's why the button was re-focus !
Thanks you ! It work perfectly !
